{
  "add_formats_to_existing": false,
  "case_sensitive": false,
  "check_for_dupes_on_ctl": false,
  "database_path": "/home/vp/library1.db",
  "filename_pattern": "(?P<title>.+) - (?P<author>[^_]+)",
  "input_format_order": [
    "EPUB",
    "AZW3",
    "MOBI",
    "LIT",
    "PRC",
    "FB2",
    "HTML",
    "HTM",
    "XHTM",
    "SHTML",
    "XHTML",
    "ZIP",
    "DOCX",
    "ODT",
    "RTF",
    "PDF",
    "TXT"
  ],
  "installation_uuid": "21414d70-97cf-4fc0-8d58-d8b60ec8ebfd",
  "isbndb_com_key": "",
  "language": null,
  "library_path": "/home/vp/cal1",
  "limit_search_columns": false,
  "limit_search_columns_to": [
    "title",
    "authors",
    "tags",
    "series",
    "publisher"
  ],
  "manage_device_metadata": "manual",
  "mark_new_books": false,
  "migrated": false,
  "network_timeout": 5,
  "new_book_tags": [],
  "output_format": "EPUB",
  "read_file_metadata": true,
  "saved_searches": {},
  "swap_author_names": false,
  "use_primary_find_in_search": true,
  "user_categories": {},
  "worker_process_priority": "normal"
}